# Generated by Django 2.2.1 on 2019-06-03 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('searchdb', '0002_auto_20190603_2034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensorvalue',
            old_name='date',
            new_name='datein',
        ),
    ]
