# Generated by Django 2.2.1 on 2019-06-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensorvalue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('cds', models.CharField(max_length=15)),
                ('led', models.IntegerField(default=0)),
            ],
        ),
    ]
